### ISSUE TITLE
Deleted my existing modules

### ISSUE THREAD

**Issue by arunoda** [mantrajs/mantrajs-atom-package#2]
At one time, when creating a module, this deleted my existing modules.
May be need to have a look at it.

**Comment by tomitrescak** [comment]
Wow. That should not happen ... But, are you sure this happened while creating a new module? The only ways I know this could happen was, when you used the context menu on mantra pane items and deleted a module from there. There is an issue with treeview and as I mentioned I think I am going to disable the context menu because of that. Could you please confirm that this was the issue? Otherwise this package is straight dangerous ;)

**Comment by tomitrescak** [comment]
I'll close this for now as I could not reporoduce. If needed we will reopen ...

**Comment by arunoda** [comment]
Yeah! It's working pretty well for me now.
Thanks.
